/* Datos reales del organigrama (2026-09-11, a petición explícita del usuario: reemplaza la
   imagen plana estructura-organizacional.png por un árbol interactivo). Todo el CONTENIDO del
   organigrama (nombres/puestos/áreas) se mantiene SIEMPRE en inglés a petición explícita
   ("el organigrama debe estar en ingles") -- independiente del idioma que tenga elegido el
   usuario en el resto de la app, por eso este archivo nunca usa i18n.

   Celular/correo/fecha de ingreso quedan null a propósito (el usuario pidió dejarlos en blanco
   por ahora, "—" en la UI) -- nunca se inventa un dato real de una persona real. photo: null
   usa un avatar con iniciales en vez de foto (Felipe/Johnatan, gente nueva sin foto todavía). */
export const ORG_CHART = {
  id: 'juan-sillas',
  name: 'Juan Sillas',
  title: null,
  area: null,
  department: null,
  manager: null,
  photo: '/organigrama/photos/juan-sillas.png',
  phone: null,
  email: null,
  hireDate: null,
  children: [
    {
      id: 'cain-bautista',
      name: 'Cain Bautista',
      title: 'Production Manager',
      area: 'Production',
      department: 'Production',
      manager: 'Juan Sillas',
      photo: '/organigrama/photos/cain-bautista.png',
      phone: null,
      email: null,
      hireDate: null,
      groupLabel: 'Operational Leadership',
      children: [
        {
          id: 'diego-zamudio',
          name: 'Diego Zamudio',
          title: 'Production Team Leader',
          area: 'Production',
          department: 'Production',
          manager: 'Cain Bautista',
          photo: '/organigrama/photos/diego-zamudio.png',
          phone: null,
          email: null,
          hireDate: null,
        },
        {
          id: 'johnatan',
          name: 'Johnatan',
          title: 'Production Team Leader',
          area: 'Production',
          department: 'Production',
          manager: 'Cain Bautista',
          photo: null,
          phone: null,
          email: null,
          hireDate: null,
        },
        {
          id: 'arturo-badillo',
          name: 'Arturo Badillo',
          title: 'Training & Coaching',
          area: 'Training & Coaching',
          department: 'Production',
          manager: 'Cain Bautista',
          photo: '/organigrama/photos/arturo-badillo.png',
          phone: null,
          email: null,
          hireDate: null,
        },
      ],
      secondGroupLabel: 'Area Leaders',
      secondGroupChildren: [
        {
          id: 'sandra-barron',
          name: 'Sandra Barrón',
          title: 'Accessories Leader',
          area: 'Accessories',
          department: 'Production',
          manager: 'Cain Bautista',
          photo: '/organigrama/photos/sandra-barron.png',
          phone: null,
          email: null,
          hireDate: null,
        },
        {
          id: 'ernesto-rivera',
          name: 'Ernesto Rivera',
          title: 'Boxes & Supplies Leader',
          area: 'Boxes & Supplies',
          department: 'Production',
          manager: 'Cain Bautista',
          photo: '/organigrama/photos/ernesto-rivera.png',
          phone: null,
          email: null,
          hireDate: null,
        },
        {
          id: 'elias',
          name: 'Elías',
          title: 'Palletizing (FFT) Team Leader',
          area: 'Palletizing (FFT)',
          department: 'Production',
          manager: 'Cain Bautista',
          photo: '/organigrama/photos/elias.png',
          phone: null,
          email: null,
          hireDate: null,
        },
      ],
    },
    {
      id: 'felipe',
      name: 'Felipe',
      title: 'Production Manager',
      area: 'Production',
      department: 'Production',
      manager: 'Juan Sillas',
      photo: null,
      phone: null,
      email: null,
      hireDate: null,
    },
  ],
}
